### ISSUE TITLE
Incorrect string value MySQL error when saving utf-8 character to database

### ISSUE THREAD

**Issue by bobbyesh** [etokrug/modua#16]
The database defautl character set is utf8, but this error occurs when saving an instance as follows:
`
        Definitions.objects.create(word_character='一定要', definition='must do something')
`

This is the error:
```
/home/bobby/projects/modua1/venv/lib/python3.4/site-packages/django/db/backends/mysql/base.py:112: Warning: Incorrect string value: '\xE4\xB8\x80\xE5\xAE\x9A...' for column 'word_character' at row 1
  return self.cursor.execute(query, args)

Note:  Saving English words works fine.

```

**Comment by etokrug** [comment]
I'm currently changing the DB to PostgreSQL. This should alleviate this problem. Once we know, I'll push to close this.

**Comment by bobbyesh** [comment]
Issued fixed with switch to PostgreSQL.
